[profile.default]
root = '../..'
src = 'packages/solidity-semantic-money'
out = 'packages/solidity-semantic-money/out'
remappings = [
    '@superfluid-finance/ethereum-contracts/contracts/=packages/ethereum-contracts/contracts/',
    'ds-test/=lib/forge-std/lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/']
