name: Reusable Workflow | Test Spec Haskell

on:
  workflow_call:

jobs:
  test-spec-haskell:
    name: Test Spec Haskell - Linux - ${{ matrix.compiler }}

    runs-on: ubuntu-latest

    continue-on-error: ${{ matrix.allow-failure }}

    strategy:
      matrix:
        include:
          - compiler: ghc-9.2.5
            devShell: ci-spec-ghc925
            allow-failure: false
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v19
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: nix shell
        run: nix develop .#${{ matrix.devShell }}

      - run: |
          nix develop .#${{ matrix.devShell }} << EOF
            cabal v2-update -v
          EOF

      - name: cache
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-${{ matrix.compiler }}-${{ github.sha }}
          path: ~/.cabal/store
          restore-keys: ${{ runner.os }}-${{ matrix.compiler }}-

      - name: lint
        run: |
          nix develop .#${{ matrix.devShell }} << EOF
            cd packages/spec-haskell
            make lint
          EOF

      - name: build
        run: |
          nix develop .#${{ matrix.devShell }} << EOF
            cd packages/spec-haskell
            make build
          EOF

      - name: tests
        run: |
          nix develop .#${{ matrix.devShell }} << EOF
            cd packages/spec-haskell
            make test
          EOF

      - name: haddock
        run: |
          nix develop .#${{ matrix.devShell }} << EOF
            cd packages/spec-haddock
            make docs-haddock
          EOF
